### ISSUE TITLE
Consider using HTML <!-- comments instead of [//]: in PR template

### ISSUE THREAD

**Issue by jcbhmr** [Andrew-Chen-Wang/.github#1]
When I first saw this:

![image](https://user-images.githubusercontent.com/61068799/224431644-e60154e0-626d-470f-8a3b-1d1838d90c9a.png)

I was very confused. Do those remarks show up? Should I delete them? Are they supposed to show up? Then I realized they were supposed to be _comments_, not malformed links.

I think a more clear and universally understood way of putting text for the submitter to see, but that doesn't appear on the final PR for other viewers (i.e. content SOLELY for the poster) should go in a `<!-- comment here -->` block.

I think this can be backed up with statistics:

`[//]:` = 285 hits [code search](https://github.com/search?q=%22%5B%2F%2F%5D%3A%22+lang%3AMarkdown+path%3A**%2FPULL_REQUEST_TEMPLATE.md&type=code) \
`<!--` = 46.3k hits [code search](https://github.com/search?q=%22%3C%21--%22+lang%3AMarkdown+path%3A**%2FPULL_REQUEST_TEMPLATE.md&type=code) \
ratio = 162:1

Anyways that's my opinion and some evidence to make the case. Whether you actually change it is totally up to you. ❤

**Comment by Andrew-Chen-Wang** [comment]
Sure works with me

**Comment by jcbhmr** [comment]
Cool! I also have some other stuff that I use that you might be interested in https://github.com/jcbhmr/.github particularly the CONTRIBUTING.md default doc and the SUPPORT.md default doc.

I've opened a PR to merge with this HTML comment thing change. #2
